import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type Dialect = "sqlite" | "postgres" | "mysql";

const TEMPLATES_ROOT = resolve(
  fileURLToPath(new URL(".", import.meta.url)),
  ".."
);
const STORAGE_ROOT = resolve(TEMPLATES_ROOT, "../storage");
const OUTPUT_PATH = resolve(
  TEMPLATES_ROOT,
  "scaffold/generated/db-schema-templates.ts"
);

const DIALECTS = [
  "sqlite",
  "postgres",
  "mysql",
] as const satisfies readonly Dialect[];

const CORE_SCHEMA_PATH_BY_DIALECT = {
  mysql: "schema/mysql.ts",
  postgres: "schema/postgres.ts",
  sqlite: "schema/sqlite.ts",
} as const satisfies Record<Dialect, string>;

const AUTH_SCHEMA_PATH_BY_DIALECT = {
  mysql: "schema/auth/mysql.ts",
  postgres: "schema/auth/postgres.ts",
  sqlite: "schema/auth/sqlite.ts",
} as const satisfies Record<Dialect, string>;

const readSchemaByDialect = async (
  pathsByDialect: Record<Dialect, string>
): Promise<Record<Dialect, string>> => {
  const entries = await Promise.all(
    DIALECTS.map(async (dialect) => {
      const path = resolve(STORAGE_ROOT, pathsByDialect[dialect]);
      return [dialect, await readFile(path, "utf8")] as const;
    })
  );

  return Object.fromEntries(entries) as Record<Dialect, string>;
};

const renderAssetFile = (input: {
  authTemplates: Record<Dialect, string>;
  coreTemplates: Record<Dialect, string>;
}): string => {
  return `// AUTO-GENERATED by scripts/build-db-schema-template-assets.ts
// Do not edit manually.

export const CORE_SCHEMA_TEMPLATE_BY_DIALECT = ${JSON.stringify(input.coreTemplates, null, 2)} as const;

export const AUTH_SCHEMA_TEMPLATE_BY_DIALECT = ${JSON.stringify(input.authTemplates, null, 2)} as const;
`;
};

const run = async (): Promise<void> => {
  const [coreTemplates, authTemplates] = await Promise.all([
    readSchemaByDialect(CORE_SCHEMA_PATH_BY_DIALECT),
    readSchemaByDialect(AUTH_SCHEMA_PATH_BY_DIALECT),
  ]);

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(
    OUTPUT_PATH,
    renderAssetFile({ authTemplates, coreTemplates }),
    "utf8"
  );
};

await run();
