import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  emitAuthDrizzleSchemaFromBetterAuthImport,
  emitCoreDrizzleSchema,
} from "./schema-foundation";

type Dialect = "sqlite" | "postgres" | "mysql";

const TEMPLATES_ROOT = resolve(
  fileURLToPath(new URL(".", import.meta.url)),
  ".."
);
const OUTPUT_PATH = resolve(
  TEMPLATES_ROOT,
  "scaffold/generated/db-schema-templates.ts"
);

const DIALECTS = [
  "sqlite",
  "postgres",
  "mysql",
] as const satisfies readonly Dialect[];

export const emitSchemaByDialect = async (input: {
  emitDialectSchema: (dialect: Dialect) => string | Promise<string>;
}): Promise<Record<Dialect, string>> => {
  const entries = await Promise.all(
    DIALECTS.map(async (dialect) => {
      return [dialect, await input.emitDialectSchema(dialect)] as const;
    })
  );

  return Object.fromEntries(entries) as Record<Dialect, string>;
};

export const renderAssetFile = (input: {
  authTemplates: Record<Dialect, string>;
  coreTemplates: Record<Dialect, string>;
}): string => {
  return `// AUTO-GENERATED by scripts/build-db-schema-template-assets.ts
// Do not edit manually.

export const CORE_SCHEMA_TEMPLATE_BY_DIALECT = ${JSON.stringify(input.coreTemplates, null, 2)} as const;

export const AUTH_SCHEMA_TEMPLATE_BY_DIALECT = ${JSON.stringify(input.authTemplates, null, 2)} as const;
`;
};

export const run = async (): Promise<void> => {
  const [coreTemplates, authTemplates] = await Promise.all([
    emitSchemaByDialect({ emitDialectSchema: emitCoreDrizzleSchema }),
    emitSchemaByDialect({
      emitDialectSchema: emitAuthDrizzleSchemaFromBetterAuthImport,
    }),
  ]);

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(
    OUTPUT_PATH,
    renderAssetFile({ authTemplates, coreTemplates }),
    "utf8"
  );
};

if (import.meta.main) {
  await run();
}
