import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    "hooks/models": "./src/hooks/models.ts",
    "hooks/types": "./src/hooks/types.ts",
    "capabilities/models": "./src/capabilities/models.ts",
    "capabilities/types": "./src/capabilities/types.ts",
    "config/models": "./src/config/models.ts",
    "config/types": "./src/config/types.ts",
    "config/utils": "./src/config/utils.ts",
    "config/messages": "./src/messages/types.ts",
    "plugins/define": "./src/plugins/define.ts",
    "plugins/models": "./src/plugins/models.ts",
    "plugins/types": "./src/plugins/types.ts",
    "database/thread": "./src/database/thread.ts",
    "database/message": "./src/database/message.ts",
    "database/ai-run": "./src/database/ai-run.ts",
    "database/ai-run-tool-call": "./src/database/ai-run-tool-call.ts",
    "database/interface": "./src/database/interface.ts",
    "model/model-ref": "./src/model/model-ref.ts",
    "model/provider-metadata": "./src/model/provider-metadata.ts",
    "platform/platform-metadata": "./src/platform/platform-metadata.ts",
    "model/catalog/openai": "./src/model/catalog/openai.ts",
    "model/catalog/anthropic": "./src/model/catalog/anthropic.ts",
    "model/catalog/google": "./src/model/catalog/google.ts",
    "model/catalog/openrouter": "./src/model/catalog/openrouter.ts",
    "model/catalog/ai-gateway": "./src/model/catalog/ai-gateway.ts",
    "model/catalog/vercel-gateway": "./src/model/catalog/vercel-gateway.ts",
  },
  format: ["esm", "cjs"],
  dts: {
    sourcemap: true,
  },
  hash: false,
  unbundle: true,
  sourcemap: true,
  clean: true,
  outDir: "./dist",
});
